/* Builds data/areas.js: Chicago's 77 community areas as simplified SVG paths,
   each with its official number, name and side of the city.
   Source: City of Chicago Data Portal, "Boundaries - Community Areas"
   (https://data.cityofchicago.org/d/igwz-8jzy), public domain.
   Run: node tools/areas.mjs  (fetches the GeoJSON; or pass a local file path) */
import { readFileSync, writeFileSync } from 'node:fs';

const SRC = 'https://data.cityofchicago.org/resource/igwz-8jzy.geojson';
const geo = process.argv[2] ? JSON.parse(readFileSync(process.argv[2], 'utf8')) : await (await fetch(SRC)).json();

/* The nine sides, by community area number, as the city's regions are
   conventionally drawn. */
const SIDES = {
  'Far North Side': [1, 2, 3, 4, 9, 10, 11, 12, 13, 14, 76, 77],
  'Northwest Side': [15, 16, 17, 18, 19, 20],
  'North Side': [5, 6, 7, 21, 22],
  'West Side': [23, 24, 25, 26, 27, 28, 29, 30, 31],
  'Central': [8, 32, 33],
  'South Side': [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 60, 69],
  'Southwest Side': [56, 57, 58, 59, 61, 62, 63, 64, 65, 66, 67, 68],
  'Far Southwest Side': [70, 71, 72, 73, 74, 75],
  'Far Southeast Side': [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55]
};
const sideOf = (n) => Object.keys(SIDES).find((s) => SIDES[s].includes(n));
const FIX = { 'OHARE': 'O’Hare', 'MCKINLEY PARK': 'McKinley Park', 'LAKE VIEW': 'Lake View' };
const title = (s) => FIX[s] || s.toLowerCase().replace(/\b[a-z]/g, (c) => c.toUpperCase());

/* Equirectangular, corrected for latitude, into a 600-wide viewBox. */
const rings = geo.features.flatMap((f) => (f.geometry.type === 'Polygon' ? [f.geometry.coordinates] : f.geometry.coordinates).flat());
const lons = rings.flat().map((p) => p[0]), lats = rings.flat().map((p) => p[1]);
const [minX, maxX, minY, maxY] = [Math.min(...lons), Math.max(...lons), Math.min(...lats), Math.max(...lats)];
const k = Math.cos(((minY + maxY) / 2) * Math.PI / 180);
const W = 600, S = W / ((maxX - minX) * k), H = Math.ceil((maxY - minY) * S);
const pt = ([x, y]) => [(x - minX) * k * S, (maxY - y) * S];

/* Douglas-Peucker, so 2 MB of boundary becomes a few dozen KB. */
function simplify(pts, tol) {
  if (pts.length < 3) return pts;
  const [a, b] = [pts[0], pts[pts.length - 1]];
  let idx = 0, max = 0;
  for (let i = 1; i < pts.length - 1; i++) {
    const [x, y] = pts[i], dx = b[0] - a[0], dy = b[1] - a[1];
    const d = Math.abs(dy * x - dx * y + b[0] * a[1] - b[1] * a[0]) / (Math.hypot(dx, dy) || 1);
    if (d > max) { max = d; idx = i; }
  }
  return max > tol ? [...simplify(pts.slice(0, idx + 1), tol).slice(0, -1), ...simplify(pts.slice(idx), tol)] : [a, b];
}
/* A ring starts and ends on the same point, which gives the line no length:
   split it at the point farthest from the start and simplify each half. */
function simplifyRing(pts, tol) {
  let far = 0, max = -1;
  pts.forEach(([x, y], i) => { const d = Math.hypot(x - pts[0][0], y - pts[0][1]); if (d > max) { max = d; far = i; } });
  return [...simplify(pts.slice(0, far + 1), tol).slice(0, -1), ...simplify(pts.slice(far), tol)];
}
const path = (polys) => polys.map((poly) => poly.map((ring) => {
  const p = simplifyRing(ring.map(pt), 0.6);
  return 'M' + p.map(([x, y]) => `${x.toFixed(1)} ${y.toFixed(1)}`).join('L') + 'Z';
}).join('')).join('');

const areas = geo.features.map((f) => {
  const n = Number(f.properties.area_numbe);
  const polys = f.geometry.type === 'Polygon' ? [f.geometry.coordinates] : f.geometry.coordinates;
  return { n, name: title(f.properties.community), side: sideOf(n), d: path(polys) };
}).sort((a, b) => a.n - b.n);
if (areas.length !== 77 || areas.some((a) => !a.side)) throw new Error('Expected 77 areas, each on a side');

writeFileSync(new URL('../data/areas.js', import.meta.url),
  `// Generated by tools/areas.mjs from the City of Chicago's community area\n// boundaries (public domain). Do not edit by hand.\n\nexport const MAP = { w: ${W}, h: ${H} };\nexport const SIDES = ${JSON.stringify(Object.keys(SIDES))};\nexport const AREAS = [\n${areas.map((a) => '  ' + JSON.stringify(a)).join(',\n')}\n];\n`);
console.log(`data/areas.js: 77 areas, ${W}x${H}`);
